<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--        <TargetFramework>net9.0</TargetFramework>-->
        <TargetFramework>net9.0-windows10.0.22621</TargetFramework>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <includeSourceRevisionInInformationalVersion>false</includeSourceRevisionInInformationalVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
        <ApplicationIcon>Assets\Images\icon.ico</ApplicationIcon>
        <AssemblyVersion>99.99</AssemblyVersion>
    </PropertyGroup>

    <PropertyGroup>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AuthentikSharp" Version="1.0.3"/>
        <PackageReference Include="Avalonia" Version="12.0.1"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="Emgu.CV.Bitmap" Version="4.13.0.5924"/>
        <PackageReference Include="LiveKit.AspNetCore.ServerSdk" Version="2.1.5"/>
        <PackageReference Include="Livekit.Rtc.Dotnet" Version="0.1.2"/>
        <PackageReference Include="Livekit.Server.Sdk.Dotnet" Version="1.2.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8"/>
        <PackageReference Include="NAudio" Version="2.3.0"/>
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0"/>
        <PackageReference Include="Updatum" Version="1.3.7"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Assets\Audio\"/>
        <Folder Include="Features\AudioCapture\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Controls\UserCard.axaml.cs">
            <DependentUpon>UserCard.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
</Project>
